[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

monitor_speed = 115200


lib_deps =
    ; LCD control (I2C backpack version)
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4

    ; JSON building/parsing for order + menu data
    bblanchon/ArduinoJson @ ^7.0.4

    ; --- Choose ONE backend option below, delete the other ---

    ; Option A: Firebase Realtime Database
    mobizt/Firebase ESP32 Client @ ^4.4.17

    ; Option B: MQTT (comment out Firebase line above if using this)
    ; knolleary/PubSubClient @ ^2.8